name       : julia
version    : 0.5.1
release    : 3
source     :
    - https://github.com/JuliaLang/julia/releases/download/v0.5.1/julia-0.5.1-full.tar.gz : 533b6427a1b01bd38ea0601f58a32d15bf403f491b8415e9ce4305b8bc83bb21
license    : MIT
component  : programming
summary    : The Julia Language - A fresh approach to technical computing.
description: |
    The Julia Language - A fresh approach to technical computing.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(libunwind)
    - llvm-devel
    - openblas-devel
    - suitesparse-devel
rundeps    :
    - libgit2
    - suitesparse
patterns   :
    - docs : [/usr/share/doc]
build      : |
    #Based off Gentoo patch
    %patch -p1 < $pkgfiles/julia-fix-llvm-linking.patch
    %make release prefix=/usr sysconfdir=/etc MARCH=x86-64 \
        LIBBLASNAME=libopenblas \
        LIBLAPACKNAME=libopenblas \
        USE_LLVM_SHLIB=1 \
        USE_SYSTEM_BLAS=1 \
        USE_SYSTEM_CURL=1 \
        USE_SYSTEM_FFTW=1 \
        USE_SYSTEM_GMP=1 \
        USE_SYSTEM_LAPACK=1 \
        USE_SYSTEM_LIBGIT2=1 \
        USE_SYSTEM_LIBSSH2=1 \
        USE_SYSTEM_LIBUNWIND=1 \
        USE_SYSTEM_LLVM=1 \
        USE_SYSTEM_MPFR=1 \
        USE_SYSTEM_SUITESPARSE=1
install    : |
    %make_install release prefix=/usr sysconfdir=/etc MARCH=x86-64 \
        LIBBLASNAME=libopenblas \
        LIBLAPACKNAME=libopenblas \
        USE_LLVM_SHLIB=1 \
        USE_SYSTEM_BLAS=1 \
        USE_SYSTEM_CURL=1 \
        USE_SYSTEM_FFTW=1 \
        USE_SYSTEM_GMP=1 \
        USE_SYSTEM_LAPACK=1 \
        USE_SYSTEM_LIBGIT2=1 \
        USE_SYSTEM_LIBSSH2=1 \
        USE_SYSTEM_LIBUNWIND=1 \
        USE_SYSTEM_LLVM=1 \
        USE_SYSTEM_MPFR=1 \
        USE_SYSTEM_SUITESPARSE=1
    # Empty folder
    rm -rf $installdir/usr/libexec
    echo '/usr/lib/julia' > julia.conf
    install -Dm00644 julia.conf $installdir/etc/ld.so.conf.d/julia.conf
