name       : julia
version    : 1.0
release    : 13
source     :
    - git|https://github.com/JuliaLang/julia.git : v1.0.0
license    : MIT
component  : programming
summary    : The Julia Language - A fresh approach to technical computing.
description: |
    The Julia Language - A fresh approach to technical computing.
builddeps  :
    - pkgconfig(fftw3)
    - pkgconfig(libgit2)
    - pkgconfig(libssh2)
    - pkgconfig(libunwind)
    - pkgconfig(libpcre2-8)
    - arpack-devel
    - openblas-devel
    - suitesparse-devel
clang      : yes
rundeps    :
    - arpack
    - libgit2
    - pcre2
    - suitesparse
patterns   :
    - docs : [/usr/share/doc]
networking : yes
build      : |
    sed -i /libcurl,CURL/d base/Makefile
    %make -j1 release prefix=/usr sysconfdir=/etc MARCH=x86-64 \
        LIBBLASNAME=libopenblas \
        LIBLAPACKNAME=libopenblas \
        USE_LLVM_SHLIB=1 \
        USE_SYSTEM_ARPACK=1 \
        USE_SYSTEM_BLAS=1 \
        USE_SYSTEM_CURL=1 \
        USE_SYSTEM_FFTW=1 \
        USE_SYSTEM_GMP=1 \
        USE_SYSTEM_LAPACK=1 \
        USE_SYSTEM_LIBGIT2=1 \
        USE_SYSTEM_LIBSSH2=1 \
        USE_SYSTEM_MPFR=1 \
        USE_SYSTEM_PCRE=1 \
        USE_SYSTEM_SUITESPARSE=1 \
        CC=clang CXX=clang++
install    : |
    %make_install -j1 release prefix=/usr sysconfdir=/etc MARCH=x86-64 \
        LIBBLASNAME=libopenblas \
        LIBLAPACKNAME=libopenblas \
        USE_LLVM_SHLIB=1 \
        USE_SYSTEM_ARPACK=1 \
        USE_SYSTEM_BLAS=1 \
        USE_SYSTEM_CURL=1 \
        USE_SYSTEM_FFTW=1 \
        USE_SYSTEM_GMP=1 \
        USE_SYSTEM_LAPACK=1 \
        USE_SYSTEM_LIBGIT2=1 \
        USE_SYSTEM_LIBSSH2=1 \
        USE_SYSTEM_MPFR=1 \
        USE_SYSTEM_PCRE=1 \
        USE_SYSTEM_SUITESPARSE=1 \
        CC=clang CXX=clang++ -j1
    # Empty folder
    rm -rf $installdir/usr/libexec
    echo '/usr/lib/julia' > julia.conf
    install -Dm00644 julia.conf $installdir/usr/share/ld.so.conf.d/julia.conf
