name       : julia
version    : 1.5.3
release    : 26
source     :
    - https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3-full.tar.gz : fb69337ca037576758547c7eed9ae8f153a9c052318327b6b7f1917408c14d91
license    : MIT
component  : programming
summary    : The Julia Language - A fresh approach to technical computing.
description: |
    Julia provides ease and expressiveness for high-level numerical computing, in the same way as languages such as R, MATLAB, and Python, but also supports general programming.
builddeps  :
    - pkgconfig(libgit2)
    - pkgconfig(libpcre2-posix)
    - pkgconfig(libssh2)
    - pkgconfig(libunwind)
    - pkgconfig(libutf8proc)
    - pkgconfig(openblas)
    - mbedtls-devel
    - suitesparse-devel
rundeps    :
    # Unfortunately Julia doesn't link against most of the libraries but calls them with `dlopen()`.
    # It also requires unversioned sonames so we're pulling in the -devel variant.
    # Some dependencies though are not listed because either dynlinked to or part of system.base.
    - arpack-devel
    - fftw-devel
    - gmp-devel
    - libgit2-devel
    - mbedtls-devel
    - mpfr-devel
    - openblas-devel
    - p7zip
    - pcre2-devel
    - suitesparse
patterns   :
    - docs : [/usr/share/doc]
networking : yes
setup      : |
    %patch -p1 < $pkgfiles/Do-not-rebuild-on-install.patch
    sed /libcurl,CURL/d -i base/Makefile
build      : |
    %make LIBBLASNAME=libopenblas \
        LIBLAPACKNAME=libopenblas \
        MARCH=x86-64 \
        USE_SYSTEM_ARPACK=1 \
        USE_SYSTEM_BLAS=1 \
        USE_SYSTEM_CURL=1 \
        USE_SYSTEM_FFTW=1 \
        USE_SYSTEM_GMP=1 \
        USE_SYSTEM_LAPACK=1 \
        USE_SYSTEM_LIBGIT2=1 \
        USE_SYSTEM_LIBSSH2=1 \
        USE_SYSTEM_LIBUNWIND=1 \
        USE_SYSTEM_LLVM=0 \
        USE_SYSTEM_MBEDTLS=1 \
        USE_SYSTEM_MPFR=1 \
        USE_SYSTEM_P7ZIP=1 \
        USE_SYSTEM_PCRE=1 \
        USE_SYSTEM_SUITESPARSE=1 \
        USE_SYSTEM_UTF8PROC=1 \
        USE_SYSTEM_ZLIB=1 \
        VERBOSE=1 \
        release
install    : |
    %make_install prefix=%PREFIX% libdir=%libdir% sysconfdir=/etc

    # The startup file is empty, and it's preferred to have it in $HOME.
    rm -rf $installdir/etc
